//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cuentas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuentas
    {
        public int id { get; set; }
        public string NombreCta { get; set; }
        public string Excento { get; set; }
        public string Banco { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<decimal> Saldo { get; set; }
    }
}
